insert into pais values ('Afganistan')
insert into pais values ('Albania')
insert into pais values ('Alemania')
insert into pais values ('Andorra')
insert into pais values ('Angola')
insert into pais values ('Antigua y Barbuda')
insert into pais values ('Arabia Saudita')
insert into pais values ('Argelia')
insert into pais values ('Argentina')
insert into pais values ('Armenia')
insert into pais values ('Australia')
insert into pais values ('Austria')
insert into pais values ('Azerbaiyán')
insert into pais values ('Bahamas')
insert into pais values ('Bangladés')
insert into pais values ('Barbados')
insert into pais values ('Baréin')
insert into pais values ('Bélgica')
insert into pais values ('Belice')
insert into pais values ('Benín')
insert into pais values ('Bielorrusia')
insert into pais values ('Birmania / Myanmar')
insert into pais values ('Bolivia')
insert into pais values ('Bosnia-Herzegovina')
insert into pais values ('Botsuana')
insert into pais values ('Brasil')
insert into pais values ('Brunei')
insert into pais values ('Bulgaria')
insert into pais values ('Burkina Faso')
insert into pais values ('Burundi')
insert into pais values ('Bután')
insert into pais values ('Cabo Verde')
insert into pais values ('Camboya')
insert into pais values ('Camerún')
insert into pais values ('Canadá')
insert into pais values ('Catar')
insert into pais values ('Chad')
insert into pais values ('Chile')
insert into pais values ('China')
insert into pais values ('Chipre')
insert into pais values ('Ciudad del Vaticano')
insert into pais values ('Colombia')
insert into pais values ('Comoras')
insert into pais values ('Corea del Norte')
insert into pais values ('Corea del Sur')
insert into pais values ('Costa de Marfil')
insert into pais values ('Costa Rica')
insert into pais values ('Croacia')
insert into pais values ('Cuba')
insert into pais values ('Dinamarca')
insert into pais values ('Dominica')
insert into pais values ('Ecuador')
insert into pais values ('Egipto')
insert into pais values ('El Salvador')
insert into pais values ('Emiratos Árabes Unidos')
insert into pais values ('Eritrea')
insert into pais values ('Eslovaquia')
insert into pais values ('Eslovenia')
insert into pais values ('España')
insert into pais values ('Estados Unidos')
insert into pais values ('Estonia')
insert into pais values ('Etiopía')
insert into pais values ('Filipinas')
insert into pais values ('Finlandia')
insert into pais values ('Fiyi')
insert into pais values ('Francia')
insert into pais values ('Gabón')
insert into pais values ('Gambia')
insert into pais values ('Georgia')
insert into pais values ('Ghana')
insert into pais values ('Granada')
insert into pais values ('Grecia')
insert into pais values ('Guatemala')
insert into pais values ('Guinea')
insert into pais values ('Guinea Ecuatorial')
insert into pais values ('Guinea-Bisáu')
insert into pais values ('Guyana')
insert into pais values ('Guyana')
insert into pais values ('Haití')
insert into pais values ('Honduras')
insert into pais values ('Hungría')
insert into pais values ('India')
insert into pais values ('Indonesia')
insert into pais values ('Irak')
insert into pais values ('Irán')
insert into pais values ('Irlanda')
insert into pais values ('Islandia')
insert into pais values ('Islas Marshall')
insert into pais values ('Islas Salomón')
insert into pais values ('Israel')
insert into pais values ('Italia')
insert into pais values ('Jamaica')
insert into pais values ('Japón')
insert into pais values ('Jordania')
insert into pais values ('Kazajistán')
insert into pais values ('Kenia')
insert into pais values ('Kirguistán')
insert into pais values ('Kiribati')
insert into pais values ('Kuwait')
insert into pais values ('Macedonia del Norte')
insert into pais values ('Madagascar')
insert into pais values ('Malasia')
insert into pais values ('Malaui')
insert into pais values ('Maldivas')
insert into pais values ('Mali / Malí')
insert into pais values ('Malta')
insert into pais values ('Marruecos')
insert into pais values ('Mauricio')
insert into pais values ('Mauritania')
insert into pais values ('México')
insert into pais values ('Micronesia')
insert into pais values ('Moldavia')
insert into pais values ('Mónaco')
insert into pais values ('Mongolia')
insert into pais values ('Montenegro')
insert into pais values ('Mozambique')
insert into pais values ('Namibia')
insert into pais values ('Nauru')
insert into pais values ('Nepal')
insert into pais values ('Nicaragua')
insert into pais values ('Níger')
insert into pais values ('Nigeria')
insert into pais values ('Noruega')
insert into pais values ('Nueva Zelanda')
insert into pais values ('Países Bajos')
insert into pais values ('Pakistán')
insert into pais values ('Palaos')
insert into pais values ('Palestina')
insert into pais values ('Panamá')
insert into pais values ('Papúa Nueva Guinea')
insert into pais values ('Paraguay')
insert into pais values ('Perú')
insert into pais values ('Polonia')
insert into pais values ('Portugal')
insert into pais values ('Reino Unido')
insert into pais values ('República Centroafricana')
insert into pais values ('República Checa / Chequia')
insert into pais values ('República del Congo')
insert into pais values ('República Democrática del Congo')
insert into pais values ('República Dominicana')
insert into pais values ('Ruanda')
insert into pais values ('Rumania')
insert into pais values ('Rusia')
insert into pais values ('Samoa')
insert into pais values ('San Cristóbal y Nieves')
insert into pais values ('San Marino')
insert into pais values ('San Vicente y las Granadinas')
insert into pais values ('Santa Lucía')
insert into pais values ('Santo Tomé y Príncipe')
insert into pais values ('Senegal')
insert into pais values ('Serbia')
insert into pais values ('Seychelles')
insert into pais values ('Sierra Leona')
insert into pais values ('Singapur')
insert into pais values ('Siria')
insert into pais values ('Somalia')
insert into pais values ('Sri Lanka')
insert into pais values ('Suazilandia / Esuatini')
insert into pais values ('Sudáfrica')
insert into pais values ('Sudán')
insert into pais values ('Sudán del Sur')
insert into pais values ('Suecia')
insert into pais values ('Suiza')
insert into pais values ('Surinam')
insert into pais values ('Tailandia')
insert into pais values ('Tanzania')
insert into pais values ('Tayikistán')
insert into pais values ('Timor Oriental')
insert into pais values ('Togo')
insert into pais values ('Tonga')
insert into pais values ('Trinidad y Tobago')
insert into pais values ('Túnez')
insert into pais values ('Turkmenistán')
insert into pais values ('Turquía')
insert into pais values ('Tuvalu')
insert into pais values ('Ucrania')
insert into pais values ('Uganda')
insert into pais values ('Uruguay')
insert into pais values ('Uzbekistán')
insert into pais values ('Vanuatu')
insert into pais values ('Venezuela')
insert into pais values ('Vietnam')
insert into pais values ('Yemen')
insert into pais values ('Yibuti')
insert into pais values ('Zambia')
insert into pais values ('Zimbabue')

insert into pais values ('sebas')

select * from pais where nombre = 'Colombia'

--insert into persona values ('Samuel Ricardo','Quintero Agudelo','18/06/1990',null,42)

select nombres, apellidos, fechaNacim, fechaFallec, paisNacim, pais.id, nombre from persona inner join pais on pais.id=persona.paisNacim
